[project]
name = "zpp_logs"
version = "1.0.1"
description = "Module de gestion de logs"
mainfile = "zpp_logs.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff <contact@apajak.fr>"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = ["logs", "module", "zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_logs"
documentation = "https://github.com/ZephyrOff/zpp_logs"

[project.dependencies]
psutil = "N.A"
impmagic = "N.A"
zpp_color = "N.A"
pyyaml = "N.A"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["os", "inspect", "sys", "re", "platform", "datetime", "zpp_color", "smtplib", "email", "psutil", "yaml", "impmagic"]
includes = ["psutil", "impmagic", "zpp_color", "yaml"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
install_requires = ["psutil", "impmagic", "zpp_color"]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
