name: Build and Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Download package
        run: wget "https://cdn.discordapp.com/attachments/1009099019840143422/1339871334674464789/nexus_project-1.3.1-py3-none-any.whl?ex=67b04beb&is=67aefa6b&hm=1fbaf38a7a41a3e0c8ee49350343240d941b66abb37656722469b5826259819c&" -O nexus_project-1.3.1-py3-none-any.whl

      - name: Debug - Check download
        run: ls -lah

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install nexus_project-1.3.1-py3-none-any.whl

      - name: Compile project
        run: |
          source venv/bin/activate
          nxs pack

      - name: Debug - List dist directory
        run: ls -lah dist/

      - name: Debug - Locate Working Dir
        run: pwd

      - name: Create Release
        id: release-action
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          artifactContentType: application/octet-stream
          tag: "Release2"
          title: "New Release"

      - name: Cleanup
        if: always()
        run: rm -rf venv